name: 24 - Github Context

on: [workflow_dispatch, push, pull_request, issues, deployment_status]

jobs:
  context-variables:
    uses: thecuong3298/api-gateway/.github/workflows/maven.yml@master
    with:
      SERVICE_NAME: "hehe"
