name: 24 - Github Context

on: [workflow_dispatch, push, pull_request, issues, deployment_status]

jobs:
  context-variables:
    runs-on: ubuntu-latest
    steps:
      - id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: $GITHUB_REPOSITORY
      - id: step2
        run: echo ${{ steps.string.outputs.lowercase }}
