name: 24 - Github Context

on: [workflow_dispatch, push, pull_request, issues, deployment_status]

jobs:
  context-variables:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "GITHUB_REPOSITORY: ${{ github.ref_name }}"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "github.repository: ${{ github.repository }}"
